// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: AppDeviceServiceActions.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - ecliptix.proto.app_device.AppDeviceServiceActions

/// Namespace containing generated types for the "ecliptix.proto.app_device.AppDeviceServiceActions" service.
public enum Ecliptix_Proto_AppDevice_AppDeviceServiceActions {
    /// Service descriptor for the "ecliptix.proto.app_device.AppDeviceServiceActions" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.app_device.AppDeviceServiceActions")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "EstablishAppDeviceEphemeralConnect" metadata.
        public enum EstablishAppDeviceEphemeralConnect {
            /// Request type for "EstablishAppDeviceEphemeralConnect".
            public typealias Input = Ecliptix_Proto_PubKeyExchange
            /// Response type for "EstablishAppDeviceEphemeralConnect".
            public typealias Output = Ecliptix_Proto_PubKeyExchange
            /// Descriptor for "EstablishAppDeviceEphemeralConnect".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.app_device.AppDeviceServiceActions"),
                method: "EstablishAppDeviceEphemeralConnect"
            )
        }
        /// Namespace for "RegisterDeviceAppIfNotExist" metadata.
        public enum RegisterDeviceAppIfNotExist {
            /// Request type for "RegisterDeviceAppIfNotExist".
            public typealias Input = Ecliptix_Proto_CipherPayload
            /// Response type for "RegisterDeviceAppIfNotExist".
            public typealias Output = Ecliptix_Proto_CipherPayload
            /// Descriptor for "RegisterDeviceAppIfNotExist".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.app_device.AppDeviceServiceActions"),
                method: "RegisterDeviceAppIfNotExist"
            )
        }
        /// Descriptors for all methods in the "ecliptix.proto.app_device.AppDeviceServiceActions" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            EstablishAppDeviceEphemeralConnect.descriptor,
            RegisterDeviceAppIfNotExist.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "ecliptix.proto.app_device.AppDeviceServiceActions" service.
    public static let ecliptix_proto_appDevice_AppDeviceServiceActions = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.app_device.AppDeviceServiceActions")
}

// MARK: ecliptix.proto.app_device.AppDeviceServiceActions (server)

extension Ecliptix_Proto_AppDevice_AppDeviceServiceActions {
    /// Streaming variant of the service protocol for the "ecliptix.proto.app_device.AppDeviceServiceActions" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "EstablishAppDeviceEphemeralConnect" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Ecliptix_Proto_PubKeyExchange` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Ecliptix_Proto_PubKeyExchange` messages.
        func establishAppDeviceEphemeralConnect(
            request: GRPCCore.StreamingServerRequest<Ecliptix_Proto_PubKeyExchange>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Ecliptix_Proto_PubKeyExchange>

        /// Handle the "RegisterDeviceAppIfNotExist" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Ecliptix_Proto_CipherPayload` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Ecliptix_Proto_CipherPayload` messages.
        func registerDeviceAppIfNotExist(
            request: GRPCCore.StreamingServerRequest<Ecliptix_Proto_CipherPayload>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Ecliptix_Proto_CipherPayload>
    }

    /// Service protocol for the "ecliptix.proto.app_device.AppDeviceServiceActions" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Ecliptix_Proto_AppDevice_AppDeviceServiceActions.StreamingServiceProtocol {
        /// Handle the "EstablishAppDeviceEphemeralConnect" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_PubKeyExchange` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Ecliptix_Proto_PubKeyExchange` message.
        func establishAppDeviceEphemeralConnect(
            request: GRPCCore.ServerRequest<Ecliptix_Proto_PubKeyExchange>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Ecliptix_Proto_PubKeyExchange>

        /// Handle the "RegisterDeviceAppIfNotExist" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_CipherPayload` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Ecliptix_Proto_CipherPayload` message.
        func registerDeviceAppIfNotExist(
            request: GRPCCore.ServerRequest<Ecliptix_Proto_CipherPayload>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Ecliptix_Proto_CipherPayload>
    }

    /// Simple service protocol for the "ecliptix.proto.app_device.AppDeviceServiceActions" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Ecliptix_Proto_AppDevice_AppDeviceServiceActions.ServiceProtocol {
        /// Handle the "EstablishAppDeviceEphemeralConnect" method.
        ///
        /// - Parameters:
        ///   - request: A `Ecliptix_Proto_PubKeyExchange` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Ecliptix_Proto_PubKeyExchange` to respond with.
        func establishAppDeviceEphemeralConnect(
            request: Ecliptix_Proto_PubKeyExchange,
            context: GRPCCore.ServerContext
        ) async throws -> Ecliptix_Proto_PubKeyExchange

        /// Handle the "RegisterDeviceAppIfNotExist" method.
        ///
        /// - Parameters:
        ///   - request: A `Ecliptix_Proto_CipherPayload` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Ecliptix_Proto_CipherPayload` to respond with.
        func registerDeviceAppIfNotExist(
            request: Ecliptix_Proto_CipherPayload,
            context: GRPCCore.ServerContext
        ) async throws -> Ecliptix_Proto_CipherPayload
    }
}

// Default implementation of 'registerMethods(with:)'.
extension Ecliptix_Proto_AppDevice_AppDeviceServiceActions.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Ecliptix_Proto_AppDevice_AppDeviceServiceActions.Method.EstablishAppDeviceEphemeralConnect.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_PubKeyExchange>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_PubKeyExchange>(),
            handler: { request, context in
                try await self.establishAppDeviceEphemeralConnect(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Ecliptix_Proto_AppDevice_AppDeviceServiceActions.Method.RegisterDeviceAppIfNotExist.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_CipherPayload>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_CipherPayload>(),
            handler: { request, context in
                try await self.registerDeviceAppIfNotExist(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension Ecliptix_Proto_AppDevice_AppDeviceServiceActions.ServiceProtocol {
    public func establishAppDeviceEphemeralConnect(
        request: GRPCCore.StreamingServerRequest<Ecliptix_Proto_PubKeyExchange>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Ecliptix_Proto_PubKeyExchange> {
        let response = try await self.establishAppDeviceEphemeralConnect(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func registerDeviceAppIfNotExist(
        request: GRPCCore.StreamingServerRequest<Ecliptix_Proto_CipherPayload>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Ecliptix_Proto_CipherPayload> {
        let response = try await self.registerDeviceAppIfNotExist(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
extension Ecliptix_Proto_AppDevice_AppDeviceServiceActions.SimpleServiceProtocol {
    public func establishAppDeviceEphemeralConnect(
        request: GRPCCore.ServerRequest<Ecliptix_Proto_PubKeyExchange>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Ecliptix_Proto_PubKeyExchange> {
        return GRPCCore.ServerResponse<Ecliptix_Proto_PubKeyExchange>(
            message: try await self.establishAppDeviceEphemeralConnect(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func registerDeviceAppIfNotExist(
        request: GRPCCore.ServerRequest<Ecliptix_Proto_CipherPayload>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Ecliptix_Proto_CipherPayload> {
        return GRPCCore.ServerResponse<Ecliptix_Proto_CipherPayload>(
            message: try await self.registerDeviceAppIfNotExist(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: ecliptix.proto.app_device.AppDeviceServiceActions (client)

extension Ecliptix_Proto_AppDevice_AppDeviceServiceActions {
    /// Generated client protocol for the "ecliptix.proto.app_device.AppDeviceServiceActions" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "EstablishAppDeviceEphemeralConnect" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_PubKeyExchange` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_PubKeyExchange` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_PubKeyExchange` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func establishAppDeviceEphemeralConnect<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_PubKeyExchange>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_PubKeyExchange>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_PubKeyExchange>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_PubKeyExchange>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "RegisterDeviceAppIfNotExist" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_CipherPayload` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_CipherPayload` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_CipherPayload` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func registerDeviceAppIfNotExist<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_CipherPayload>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_CipherPayload>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_CipherPayload>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_CipherPayload>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "ecliptix.proto.app_device.AppDeviceServiceActions" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "EstablishAppDeviceEphemeralConnect" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_PubKeyExchange` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_PubKeyExchange` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_PubKeyExchange` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func establishAppDeviceEphemeralConnect<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_PubKeyExchange>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_PubKeyExchange>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_PubKeyExchange>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_PubKeyExchange>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_AppDevice_AppDeviceServiceActions.Method.EstablishAppDeviceEphemeralConnect.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "RegisterDeviceAppIfNotExist" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_CipherPayload` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_CipherPayload` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_CipherPayload` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func registerDeviceAppIfNotExist<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_CipherPayload>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_CipherPayload>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_CipherPayload>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_CipherPayload>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_AppDevice_AppDeviceServiceActions.Method.RegisterDeviceAppIfNotExist.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Ecliptix_Proto_AppDevice_AppDeviceServiceActions.ClientProtocol {
    /// Call the "EstablishAppDeviceEphemeralConnect" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_PubKeyExchange` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func establishAppDeviceEphemeralConnect<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_PubKeyExchange>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_PubKeyExchange>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.establishAppDeviceEphemeralConnect(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_PubKeyExchange>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_PubKeyExchange>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RegisterDeviceAppIfNotExist" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_CipherPayload` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func registerDeviceAppIfNotExist<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_CipherPayload>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_CipherPayload>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.registerDeviceAppIfNotExist(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_CipherPayload>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_CipherPayload>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Ecliptix_Proto_AppDevice_AppDeviceServiceActions.ClientProtocol {
    /// Call the "EstablishAppDeviceEphemeralConnect" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func establishAppDeviceEphemeralConnect<Result>(
        _ message: Ecliptix_Proto_PubKeyExchange,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_PubKeyExchange>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_PubKeyExchange>(
            message: message,
            metadata: metadata
        )
        return try await self.establishAppDeviceEphemeralConnect(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RegisterDeviceAppIfNotExist" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func registerDeviceAppIfNotExist<Result>(
        _ message: Ecliptix_Proto_CipherPayload,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_CipherPayload>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_CipherPayload>(
            message: message,
            metadata: metadata
        )
        return try await self.registerDeviceAppIfNotExist(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}