//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: HealthCheck.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Ecliptix_Proto_HealthCheckClient`, then call methods of this protocol to make API calls.
internal protocol Ecliptix_Proto_HealthCheckClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Ecliptix_Proto_HealthCheckClientInterceptorFactoryProtocol? { get }

  func sayHello(
    _ request: Ecliptix_Proto_HelloRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Ecliptix_Proto_HelloRequest, Ecliptix_Proto_HelloReply>
}

extension Ecliptix_Proto_HealthCheckClientProtocol {
  internal var serviceName: String {
    return "ecliptix.proto.HealthCheck"
  }

  /// Unary call to SayHello
  ///
  /// - Parameters:
  ///   - request: Request to send to SayHello.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func sayHello(
    _ request: Ecliptix_Proto_HelloRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ecliptix_Proto_HelloRequest, Ecliptix_Proto_HelloReply> {
    return self.makeUnaryCall(
      path: Ecliptix_Proto_HealthCheckClientMetadata.Methods.sayHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Ecliptix_Proto_HealthCheckClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Ecliptix_Proto_HealthCheckNIOClient")
internal final class Ecliptix_Proto_HealthCheckClient: Ecliptix_Proto_HealthCheckClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Ecliptix_Proto_HealthCheckClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Ecliptix_Proto_HealthCheckClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the ecliptix.proto.HealthCheck service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ecliptix_Proto_HealthCheckClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Ecliptix_Proto_HealthCheckNIOClient: Ecliptix_Proto_HealthCheckClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Ecliptix_Proto_HealthCheckClientInterceptorFactoryProtocol?

  /// Creates a client for the ecliptix.proto.HealthCheck service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ecliptix_Proto_HealthCheckClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Ecliptix_Proto_HealthCheckAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Ecliptix_Proto_HealthCheckClientInterceptorFactoryProtocol? { get }

  func makeSayHelloCall(
    _ request: Ecliptix_Proto_HelloRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ecliptix_Proto_HelloRequest, Ecliptix_Proto_HelloReply>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Ecliptix_Proto_HealthCheckAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Ecliptix_Proto_HealthCheckClientMetadata.serviceDescriptor
  }

  internal var interceptors: Ecliptix_Proto_HealthCheckClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeSayHelloCall(
    _ request: Ecliptix_Proto_HelloRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ecliptix_Proto_HelloRequest, Ecliptix_Proto_HelloReply> {
    return self.makeAsyncUnaryCall(
      path: Ecliptix_Proto_HealthCheckClientMetadata.Methods.sayHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Ecliptix_Proto_HealthCheckAsyncClientProtocol {
  internal func sayHello(
    _ request: Ecliptix_Proto_HelloRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Ecliptix_Proto_HelloReply {
    return try await self.performAsyncUnaryCall(
      path: Ecliptix_Proto_HealthCheckClientMetadata.Methods.sayHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Ecliptix_Proto_HealthCheckAsyncClient: Ecliptix_Proto_HealthCheckAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Ecliptix_Proto_HealthCheckClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ecliptix_Proto_HealthCheckClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Ecliptix_Proto_HealthCheckClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'sayHello'.
  func makeSayHelloInterceptors() -> [ClientInterceptor<Ecliptix_Proto_HelloRequest, Ecliptix_Proto_HelloReply>]
}

internal enum Ecliptix_Proto_HealthCheckClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "HealthCheck",
    fullName: "ecliptix.proto.HealthCheck",
    methods: [
      Ecliptix_Proto_HealthCheckClientMetadata.Methods.sayHello,
    ]
  )

  internal enum Methods {
    internal static let sayHello = GRPCMethodDescriptor(
      name: "SayHello",
      path: "/ecliptix.proto.HealthCheck/SayHello",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Ecliptix_Proto_HealthCheckProvider: CallHandlerProvider {
  var interceptors: Ecliptix_Proto_HealthCheckServerInterceptorFactoryProtocol? { get }

  func sayHello(request: Ecliptix_Proto_HelloRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Ecliptix_Proto_HelloReply>
}

extension Ecliptix_Proto_HealthCheckProvider {
  internal var serviceName: Substring {
    return Ecliptix_Proto_HealthCheckServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SayHello":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Ecliptix_Proto_HelloRequest>(),
        responseSerializer: ProtobufSerializer<Ecliptix_Proto_HelloReply>(),
        interceptors: self.interceptors?.makeSayHelloInterceptors() ?? [],
        userFunction: self.sayHello(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Ecliptix_Proto_HealthCheckAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Ecliptix_Proto_HealthCheckServerInterceptorFactoryProtocol? { get }

  func sayHello(
    request: Ecliptix_Proto_HelloRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Ecliptix_Proto_HelloReply
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Ecliptix_Proto_HealthCheckAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Ecliptix_Proto_HealthCheckServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Ecliptix_Proto_HealthCheckServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Ecliptix_Proto_HealthCheckServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SayHello":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Ecliptix_Proto_HelloRequest>(),
        responseSerializer: ProtobufSerializer<Ecliptix_Proto_HelloReply>(),
        interceptors: self.interceptors?.makeSayHelloInterceptors() ?? [],
        wrapping: { try await self.sayHello(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Ecliptix_Proto_HealthCheckServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'sayHello'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSayHelloInterceptors() -> [ServerInterceptor<Ecliptix_Proto_HelloRequest, Ecliptix_Proto_HelloReply>]
}

internal enum Ecliptix_Proto_HealthCheckServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "HealthCheck",
    fullName: "ecliptix.proto.HealthCheck",
    methods: [
      Ecliptix_Proto_HealthCheckServerMetadata.Methods.sayHello,
    ]
  )

  internal enum Methods {
    internal static let sayHello = GRPCMethodDescriptor(
      name: "SayHello",
      path: "/ecliptix.proto.HealthCheck/SayHello",
      type: GRPCCallType.unary
    )
  }
}
