//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: MembershipServices.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Ecliptix_Proto_Membership_MembershipServicesClient`, then call methods of this protocol to make API calls.
internal protocol Ecliptix_Proto_Membership_MembershipServicesClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Ecliptix_Proto_Membership_MembershipServicesClientInterceptorFactoryProtocol? { get }

  func opaqueRegistrationInitRequest(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions?
  ) -> UnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>

  func opaqueRegistrationCompleteRequest(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions?
  ) -> UnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>

  func opaqueSignInInitRequest(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions?
  ) -> UnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>

  func opaqueSignInCompleteRequest(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions?
  ) -> UnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>
}

extension Ecliptix_Proto_Membership_MembershipServicesClientProtocol {
  internal var serviceName: String {
    return "ecliptix.proto.membership.MembershipServices"
  }

  /// Unary call to OpaqueRegistrationInitRequest
  ///
  /// - Parameters:
  ///   - request: Request to send to OpaqueRegistrationInitRequest.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func opaqueRegistrationInitRequest(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload> {
    return self.makeUnaryCall(
      path: Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueRegistrationInitRequest.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpaqueRegistrationInitRequestInterceptors() ?? []
    )
  }

  /// Unary call to OpaqueRegistrationCompleteRequest
  ///
  /// - Parameters:
  ///   - request: Request to send to OpaqueRegistrationCompleteRequest.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func opaqueRegistrationCompleteRequest(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload> {
    return self.makeUnaryCall(
      path: Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueRegistrationCompleteRequest.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpaqueRegistrationCompleteRequestInterceptors() ?? []
    )
  }

  /// Unary call to OpaqueSignInInitRequest
  ///
  /// - Parameters:
  ///   - request: Request to send to OpaqueSignInInitRequest.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func opaqueSignInInitRequest(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload> {
    return self.makeUnaryCall(
      path: Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueSignInInitRequest.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpaqueSignInInitRequestInterceptors() ?? []
    )
  }

  /// Unary call to OpaqueSignInCompleteRequest
  ///
  /// - Parameters:
  ///   - request: Request to send to OpaqueSignInCompleteRequest.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func opaqueSignInCompleteRequest(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload> {
    return self.makeUnaryCall(
      path: Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueSignInCompleteRequest.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpaqueSignInCompleteRequestInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Ecliptix_Proto_Membership_MembershipServicesClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Ecliptix_Proto_Membership_MembershipServicesNIOClient")
internal final class Ecliptix_Proto_Membership_MembershipServicesClient: Ecliptix_Proto_Membership_MembershipServicesClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Ecliptix_Proto_Membership_MembershipServicesClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Ecliptix_Proto_Membership_MembershipServicesClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the ecliptix.proto.membership.MembershipServices service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ecliptix_Proto_Membership_MembershipServicesClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Ecliptix_Proto_Membership_MembershipServicesNIOClient: Ecliptix_Proto_Membership_MembershipServicesClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Ecliptix_Proto_Membership_MembershipServicesClientInterceptorFactoryProtocol?

  /// Creates a client for the ecliptix.proto.membership.MembershipServices service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ecliptix_Proto_Membership_MembershipServicesClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Ecliptix_Proto_Membership_MembershipServicesAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Ecliptix_Proto_Membership_MembershipServicesClientInterceptorFactoryProtocol? { get }

  func makeOpaqueRegistrationInitRequestCall(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>

  func makeOpaqueRegistrationCompleteRequestCall(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>

  func makeOpaqueSignInInitRequestCall(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>

  func makeOpaqueSignInCompleteRequestCall(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Ecliptix_Proto_Membership_MembershipServicesAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Ecliptix_Proto_Membership_MembershipServicesClientMetadata.serviceDescriptor
  }

  internal var interceptors: Ecliptix_Proto_Membership_MembershipServicesClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeOpaqueRegistrationInitRequestCall(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload> {
    return self.makeAsyncUnaryCall(
      path: Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueRegistrationInitRequest.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpaqueRegistrationInitRequestInterceptors() ?? []
    )
  }

  internal func makeOpaqueRegistrationCompleteRequestCall(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload> {
    return self.makeAsyncUnaryCall(
      path: Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueRegistrationCompleteRequest.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpaqueRegistrationCompleteRequestInterceptors() ?? []
    )
  }

  internal func makeOpaqueSignInInitRequestCall(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload> {
    return self.makeAsyncUnaryCall(
      path: Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueSignInInitRequest.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpaqueSignInInitRequestInterceptors() ?? []
    )
  }

  internal func makeOpaqueSignInCompleteRequestCall(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload> {
    return self.makeAsyncUnaryCall(
      path: Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueSignInCompleteRequest.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpaqueSignInCompleteRequestInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Ecliptix_Proto_Membership_MembershipServicesAsyncClientProtocol {
  internal func opaqueRegistrationInitRequest(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions? = nil
  ) async throws -> Ecliptix_Proto_CipherPayload {
    return try await self.performAsyncUnaryCall(
      path: Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueRegistrationInitRequest.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpaqueRegistrationInitRequestInterceptors() ?? []
    )
  }

  internal func opaqueRegistrationCompleteRequest(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions? = nil
  ) async throws -> Ecliptix_Proto_CipherPayload {
    return try await self.performAsyncUnaryCall(
      path: Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueRegistrationCompleteRequest.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpaqueRegistrationCompleteRequestInterceptors() ?? []
    )
  }

  internal func opaqueSignInInitRequest(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions? = nil
  ) async throws -> Ecliptix_Proto_CipherPayload {
    return try await self.performAsyncUnaryCall(
      path: Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueSignInInitRequest.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpaqueSignInInitRequestInterceptors() ?? []
    )
  }

  internal func opaqueSignInCompleteRequest(
    _ request: Ecliptix_Proto_CipherPayload,
    callOptions: CallOptions? = nil
  ) async throws -> Ecliptix_Proto_CipherPayload {
    return try await self.performAsyncUnaryCall(
      path: Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueSignInCompleteRequest.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeOpaqueSignInCompleteRequestInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Ecliptix_Proto_Membership_MembershipServicesAsyncClient: Ecliptix_Proto_Membership_MembershipServicesAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Ecliptix_Proto_Membership_MembershipServicesClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ecliptix_Proto_Membership_MembershipServicesClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Ecliptix_Proto_Membership_MembershipServicesClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'opaqueRegistrationInitRequest'.
  func makeOpaqueRegistrationInitRequestInterceptors() -> [ClientInterceptor<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>]

  /// - Returns: Interceptors to use when invoking 'opaqueRegistrationCompleteRequest'.
  func makeOpaqueRegistrationCompleteRequestInterceptors() -> [ClientInterceptor<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>]

  /// - Returns: Interceptors to use when invoking 'opaqueSignInInitRequest'.
  func makeOpaqueSignInInitRequestInterceptors() -> [ClientInterceptor<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>]

  /// - Returns: Interceptors to use when invoking 'opaqueSignInCompleteRequest'.
  func makeOpaqueSignInCompleteRequestInterceptors() -> [ClientInterceptor<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>]
}

internal enum Ecliptix_Proto_Membership_MembershipServicesClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MembershipServices",
    fullName: "ecliptix.proto.membership.MembershipServices",
    methods: [
      Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueRegistrationInitRequest,
      Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueRegistrationCompleteRequest,
      Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueSignInInitRequest,
      Ecliptix_Proto_Membership_MembershipServicesClientMetadata.Methods.opaqueSignInCompleteRequest,
    ]
  )

  internal enum Methods {
    internal static let opaqueRegistrationInitRequest = GRPCMethodDescriptor(
      name: "OpaqueRegistrationInitRequest",
      path: "/ecliptix.proto.membership.MembershipServices/OpaqueRegistrationInitRequest",
      type: GRPCCallType.unary
    )

    internal static let opaqueRegistrationCompleteRequest = GRPCMethodDescriptor(
      name: "OpaqueRegistrationCompleteRequest",
      path: "/ecliptix.proto.membership.MembershipServices/OpaqueRegistrationCompleteRequest",
      type: GRPCCallType.unary
    )

    internal static let opaqueSignInInitRequest = GRPCMethodDescriptor(
      name: "OpaqueSignInInitRequest",
      path: "/ecliptix.proto.membership.MembershipServices/OpaqueSignInInitRequest",
      type: GRPCCallType.unary
    )

    internal static let opaqueSignInCompleteRequest = GRPCMethodDescriptor(
      name: "OpaqueSignInCompleteRequest",
      path: "/ecliptix.proto.membership.MembershipServices/OpaqueSignInCompleteRequest",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Ecliptix_Proto_Membership_MembershipServicesProvider: CallHandlerProvider {
  var interceptors: Ecliptix_Proto_Membership_MembershipServicesServerInterceptorFactoryProtocol? { get }

  func opaqueRegistrationInitRequest(request: Ecliptix_Proto_CipherPayload, context: StatusOnlyCallContext) -> EventLoopFuture<Ecliptix_Proto_CipherPayload>

  func opaqueRegistrationCompleteRequest(request: Ecliptix_Proto_CipherPayload, context: StatusOnlyCallContext) -> EventLoopFuture<Ecliptix_Proto_CipherPayload>

  func opaqueSignInInitRequest(request: Ecliptix_Proto_CipherPayload, context: StatusOnlyCallContext) -> EventLoopFuture<Ecliptix_Proto_CipherPayload>

  func opaqueSignInCompleteRequest(request: Ecliptix_Proto_CipherPayload, context: StatusOnlyCallContext) -> EventLoopFuture<Ecliptix_Proto_CipherPayload>
}

extension Ecliptix_Proto_Membership_MembershipServicesProvider {
  internal var serviceName: Substring {
    return Ecliptix_Proto_Membership_MembershipServicesServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "OpaqueRegistrationInitRequest":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Ecliptix_Proto_CipherPayload>(),
        responseSerializer: ProtobufSerializer<Ecliptix_Proto_CipherPayload>(),
        interceptors: self.interceptors?.makeOpaqueRegistrationInitRequestInterceptors() ?? [],
        userFunction: self.opaqueRegistrationInitRequest(request:context:)
      )

    case "OpaqueRegistrationCompleteRequest":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Ecliptix_Proto_CipherPayload>(),
        responseSerializer: ProtobufSerializer<Ecliptix_Proto_CipherPayload>(),
        interceptors: self.interceptors?.makeOpaqueRegistrationCompleteRequestInterceptors() ?? [],
        userFunction: self.opaqueRegistrationCompleteRequest(request:context:)
      )

    case "OpaqueSignInInitRequest":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Ecliptix_Proto_CipherPayload>(),
        responseSerializer: ProtobufSerializer<Ecliptix_Proto_CipherPayload>(),
        interceptors: self.interceptors?.makeOpaqueSignInInitRequestInterceptors() ?? [],
        userFunction: self.opaqueSignInInitRequest(request:context:)
      )

    case "OpaqueSignInCompleteRequest":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Ecliptix_Proto_CipherPayload>(),
        responseSerializer: ProtobufSerializer<Ecliptix_Proto_CipherPayload>(),
        interceptors: self.interceptors?.makeOpaqueSignInCompleteRequestInterceptors() ?? [],
        userFunction: self.opaqueSignInCompleteRequest(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Ecliptix_Proto_Membership_MembershipServicesAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Ecliptix_Proto_Membership_MembershipServicesServerInterceptorFactoryProtocol? { get }

  func opaqueRegistrationInitRequest(
    request: Ecliptix_Proto_CipherPayload,
    context: GRPCAsyncServerCallContext
  ) async throws -> Ecliptix_Proto_CipherPayload

  func opaqueRegistrationCompleteRequest(
    request: Ecliptix_Proto_CipherPayload,
    context: GRPCAsyncServerCallContext
  ) async throws -> Ecliptix_Proto_CipherPayload

  func opaqueSignInInitRequest(
    request: Ecliptix_Proto_CipherPayload,
    context: GRPCAsyncServerCallContext
  ) async throws -> Ecliptix_Proto_CipherPayload

  func opaqueSignInCompleteRequest(
    request: Ecliptix_Proto_CipherPayload,
    context: GRPCAsyncServerCallContext
  ) async throws -> Ecliptix_Proto_CipherPayload
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Ecliptix_Proto_Membership_MembershipServicesAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Ecliptix_Proto_Membership_MembershipServicesServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Ecliptix_Proto_Membership_MembershipServicesServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Ecliptix_Proto_Membership_MembershipServicesServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "OpaqueRegistrationInitRequest":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Ecliptix_Proto_CipherPayload>(),
        responseSerializer: ProtobufSerializer<Ecliptix_Proto_CipherPayload>(),
        interceptors: self.interceptors?.makeOpaqueRegistrationInitRequestInterceptors() ?? [],
        wrapping: { try await self.opaqueRegistrationInitRequest(request: $0, context: $1) }
      )

    case "OpaqueRegistrationCompleteRequest":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Ecliptix_Proto_CipherPayload>(),
        responseSerializer: ProtobufSerializer<Ecliptix_Proto_CipherPayload>(),
        interceptors: self.interceptors?.makeOpaqueRegistrationCompleteRequestInterceptors() ?? [],
        wrapping: { try await self.opaqueRegistrationCompleteRequest(request: $0, context: $1) }
      )

    case "OpaqueSignInInitRequest":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Ecliptix_Proto_CipherPayload>(),
        responseSerializer: ProtobufSerializer<Ecliptix_Proto_CipherPayload>(),
        interceptors: self.interceptors?.makeOpaqueSignInInitRequestInterceptors() ?? [],
        wrapping: { try await self.opaqueSignInInitRequest(request: $0, context: $1) }
      )

    case "OpaqueSignInCompleteRequest":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Ecliptix_Proto_CipherPayload>(),
        responseSerializer: ProtobufSerializer<Ecliptix_Proto_CipherPayload>(),
        interceptors: self.interceptors?.makeOpaqueSignInCompleteRequestInterceptors() ?? [],
        wrapping: { try await self.opaqueSignInCompleteRequest(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Ecliptix_Proto_Membership_MembershipServicesServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'opaqueRegistrationInitRequest'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeOpaqueRegistrationInitRequestInterceptors() -> [ServerInterceptor<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>]

  /// - Returns: Interceptors to use when handling 'opaqueRegistrationCompleteRequest'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeOpaqueRegistrationCompleteRequestInterceptors() -> [ServerInterceptor<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>]

  /// - Returns: Interceptors to use when handling 'opaqueSignInInitRequest'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeOpaqueSignInInitRequestInterceptors() -> [ServerInterceptor<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>]

  /// - Returns: Interceptors to use when handling 'opaqueSignInCompleteRequest'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeOpaqueSignInCompleteRequestInterceptors() -> [ServerInterceptor<Ecliptix_Proto_CipherPayload, Ecliptix_Proto_CipherPayload>]
}

internal enum Ecliptix_Proto_Membership_MembershipServicesServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MembershipServices",
    fullName: "ecliptix.proto.membership.MembershipServices",
    methods: [
      Ecliptix_Proto_Membership_MembershipServicesServerMetadata.Methods.opaqueRegistrationInitRequest,
      Ecliptix_Proto_Membership_MembershipServicesServerMetadata.Methods.opaqueRegistrationCompleteRequest,
      Ecliptix_Proto_Membership_MembershipServicesServerMetadata.Methods.opaqueSignInInitRequest,
      Ecliptix_Proto_Membership_MembershipServicesServerMetadata.Methods.opaqueSignInCompleteRequest,
    ]
  )

  internal enum Methods {
    internal static let opaqueRegistrationInitRequest = GRPCMethodDescriptor(
      name: "OpaqueRegistrationInitRequest",
      path: "/ecliptix.proto.membership.MembershipServices/OpaqueRegistrationInitRequest",
      type: GRPCCallType.unary
    )

    internal static let opaqueRegistrationCompleteRequest = GRPCMethodDescriptor(
      name: "OpaqueRegistrationCompleteRequest",
      path: "/ecliptix.proto.membership.MembershipServices/OpaqueRegistrationCompleteRequest",
      type: GRPCCallType.unary
    )

    internal static let opaqueSignInInitRequest = GRPCMethodDescriptor(
      name: "OpaqueSignInInitRequest",
      path: "/ecliptix.proto.membership.MembershipServices/OpaqueSignInInitRequest",
      type: GRPCCallType.unary
    )

    internal static let opaqueSignInCompleteRequest = GRPCMethodDescriptor(
      name: "OpaqueSignInCompleteRequest",
      path: "/ecliptix.proto.membership.MembershipServices/OpaqueSignInCompleteRequest",
      type: GRPCCallType.unary
    )
  }
}
